name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Build and Deploy stage
      run: | 
        git config --global user.email "esd14i017@iiitdm.ac.in"
        git config --global user.name "sravan7"
        ssh -T git@github.com 
        npm run deploy
      env:
        CI: true
